### ISSUE TITLE
expr.npy, expr_max.npy, expr_min.npy. are not generated

### ISSUE THREAD

**Issue by zz12138zz** [flyingshan/nerfblendshape-unofficial#2]
You comment the function named extract_blendshape, so expr.npy, expr_max.npy, expr_min.npy. are not generated. And It seems that you don't provide data_utils/bs_solver/inference.py. If possible, could you publish this script?

**Comment by flyingshan** [comment]
Sorry, you can refer to ‘Usage notice’ section in README. This implementation relies on a private blendshape extractor which can not be open-source, so you could try using the FaceWarehouse from the original paper or using other blendshape basis like BFM2009.

**Comment by zz12138zz** [comment]
Thanks for your kindness, I'll try it. And again,  thanks for sharing your impelemention of training code.
