### ISSUE TITLE
眨眼的时候画面会抖动

### ISSUE THREAD

**Issue by ZardYuan** [flyingshan/nerfblendshape-unofficial#3]
您好，我在测试训练好的模型时，在不说话的时候如果眨眼，人脸图像会闪一下，请问您有遇到这个问题吗？

**Comment by flyingshan** [comment]
这个看目前我训练得到的demo没有出现这个问题，但是之前我好像遇到过。我猜测可能是因为如果你提的表情系数是基于BFM基地，那控制眨眼没有单独的维度，导致不容易学习，所以表情系数出现误差时会影响整体效果。

**Comment by ZardYuan** [comment]
好的，感谢
